name: Docker Image CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker build -t projectsbymw/wisecow:latest .
          docker login -u projectsbymw -p ${{ secrets.DOCKER_PASSWORD }}
          docker push projectsbymw/wisecow:latest
    - name: Deploy the image to Kubernetes
      run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
