name: Docker Image CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker build -t projectsbymw/wisecow:latest .
          docker login -u projectsbymw -p ${{ secrets.DOCKER_PASSWORD }}
          docker push projectsbymw/wisecow:latest
